# Generated by Django 4.0.4 on 2022-04-28 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entso_unit_id', models.CharField(default=None, max_length=1024, null=True)),
                ('platts_unit_id', models.CharField(default=None, max_length=1024, null=True)),
                ('gppd_plant_id', models.CharField(default=None, max_length=1024, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'mappings',
                'db_table': 'mapping',
                'ordering': ['-updatedAt'],
            },
        ),
        migrations.RenameModel(
            old_name='Platts',
            new_name='Platt',
        ),
        migrations.AlterModelTable(
            name='platt',
            table='platt',
        ),
    ]
