version: '3'
services:
  django_gunicorn:
    volumes:
      - static:/static
      - ./:/code
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
  nginx:
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - django_gunicorn
volumes:
  static: