# Generated by Django 4.0.4 on 2022-04-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mapping_rename_platts_platt_alter_platt_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='entso',
            name='mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gppd',
            name='mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platt',
            name='mapped',
            field=models.BooleanField(default=False),
        ),
    ]
